### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | ➡️  Pull `dev` into `master` to release v2.1.0 of the module.<br/><br/>Note that [some of the 2.1.0 changes](https://github.com/PrestaShop/dashactivity/commits/master) have already been pushed (wrongfully) into `master`, such as https://github.com/PrestaShop/dashactivity/pull/16 or https://github.com/PrestaShop/dashactivity/pull/15
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | this module version is compatible with PrestaShop >= 1.7.7
| Fixed ticket?     | 
| How to test?      | Please perform a regular module test campaign
| Possible impacts? |

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @matks,

I checked this PR with 1.7.7.x => OK :heavy_check_mark: 
I checked this PR with develop => OK :heavy_check_mark: 
I have only one issue during the upgrade in the PS1769:
Steps to reproduce the issue:

1. Install PS1769
2. Dashactivity module v2.0.2 is installed
3. Try to upload the zip of the release 2.1.0 
image
4. Search for the Dashactivity module in the BO > Module manager page
5. see error
image


When I install the module in PS1769 => OK
image

Thank you!

**Comment by PierreRambaud** [comment]
This new version is not compatible with 1.7.6.9 :thinking: 
https://github.com/PrestaShop/dashactivity/pull/25/files#diff-495cc167b74e91fc2169d13efa6867d3bb80664ef382c950cf0fd72cfed7f4cbR48

**Comment by khouloudbelguith** [comment]
Hi @PierreRambaud,

> This new version is not compatible with 1.7.6.9 
> https://github.com/PrestaShop/dashactivity/pull/25/files#diff-495cc167b74e91fc2169d13efa6867d3bb80664ef382c950cf0fd72cfed7f4cbR48

Yes exactly, but we can upgrade the module successfully, which is NOK.
The install of the module is OK.

Thank you!

**Comment by matks** [comment]
It seems I fail to find time to finish this 😞

**Pull request closed without merging**
