### PR TITLE
Fix: BO - dashactivity - module can't be SAVED properly

### LINKED ISSUE #37033: BO - dashactivity - module can't be SAVED properly
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Related to https://github.com/PrestaShop/PrestaShop/issues/34326

When I refresh my page, I lose my configuration

https://github.com/user-attachments/assets/0f0dbb78-59bc-49d3-a68b-38e95307efaa

### Expected behavior

The configuration should be saved

### Steps to reproduce

1. Go to BO > Dashboard
2. Configure Activity Overview > Edit configuration as you want > Save
3. Click on Configure again, see the data is saved
4. Refresh your page > Click Configure again, see the data is not saved :x:

### PrestaShop version(s) where the bug happened

8.2.0, develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

Dashboard Activity v2.1.1

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by Codencode**
Added method "saveDashConfig"

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | The configuration should be saved
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#37033
| How to test?  |

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @Codencode!

This is your first pull request on [dashactivity](https://github.com/PrestaShop/dashactivity/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Review by Hlavtox — DISMISSED** [review]

**Comment by florine2623** [comment]
Thanks for the PR.
Some checks were not successful, could you check @Codencode ?

**Comment by Codencode** [comment]
> [florine2623](/florine2623)

Hi @florine2623,
I don’t think I can fix it because, from what I understand, in the definition of the `ModuleCode::getPermission()` method, the first parameter is defined as `array`, whereas it should be `string`.

**PS 1.7.7.8**
```php
    /**
     * Check employee permission for module.
     *
     * @param array $variable (action)
     * @param Employee $employee
     *
     * @return bool if module can be transplanted on hook
     */
    public function getPermission($variable, $employee = null)
    {
        return Module::getPermissionStatic($this->id, $variable, $employee);
    }
```
https://github.com/PrestaShop/PrestaShop/blob/753bc2441bc21d79a366f3c7566a03da1ac915eb/classes/module/Module.php#L2768-L2779

**PS 8.2.0**
```php
    /**
     * Check employee permission for module.
     *
     * @param string $variable (action)
     * @param Employee $employee
     *
     * @return bool if module can be transplanted on hook
     */
    public function getPermission($variable, $employee = null)
    {
        return Module::getPermissionStatic($this->id, $variable, $employee);
    }
```
https://github.com/PrestaShop/PrestaShop/blob/327c9e42b556fcd676ff02376c00d8d8c3521061/classes/module/Module.php#L2587-L2598

I believe we should simply ignore the warning.

**Comment by Hlavtox** [comment]
@Codencode Yeah, just add this error here. :-) 

https://github.com/PrestaShop/dashactivity/blob/dev/tests/phpstan/phpstan-1.7.7.neon

and here also, because in 1.7.8 it's still an array in the docs and it will also scream at you

https://github.com/PrestaShop/dashactivity/blob/dev/tests/phpstan/phpstan-1.7.8.neon

**Comment by Codencode** [comment]
> @Codencode Yeah, just add this error here. :-)
> 
> https://github.com/PrestaShop/dashactivity/blob/dev/tests/phpstan/phpstan-1.7.7.neon
> 
> and here also, because in 1.7.8 it's still an array in the docs and it will also scream at you
> 
> https://github.com/PrestaShop/dashactivity/blob/dev/tests/phpstan/phpstan-1.7.8.neon

@Hlavtox,
I hope I did well, I added the errors to the files in my repository and uploaded them.
I never added "ignoreErrors"

Thanks!

**Comment by Hlavtox** [comment]
@Codencode Good job, all good now! :-)

**Comment by Hlavtox** [comment]
@florine2623 Ready to go! :-)

**Comment by Codencode** [comment]
> @Codencode Good job, all good now! :-)

@Hlavtox Thank you!

**Review by florine2623 — APPROVED** [review]
Hello @Codencode ,

Thanks for the PR !

Wrks as expected as you can see :

https://github.com/user-attachments/assets/363fe4d0-d2a2-40de-bd11-cbb897048d78



It is QA ✅

**Comment by Hlavtox** [comment]
Thanks everyone!

**Pull request merged**
