### PR TITLE
Update Short description and logo

### PR DESCRIPTION
**Pull request by Julievrz**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Update short description and logo.
| Type?         | improvement 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/15858
| How to test?  | Please check that short description and logo are updated.

### CODE REVIEW

**Comment by Julievrz** [comment]
I couldn't find the short description in dashactivity.php ... I would like to change the short description to "Check in one glance what is happening on your store with a list of KPI on your dashboard."

**Comment by atomiix** [comment]
@Julievrz I added the short description ;)

**Review by atomiix — APPROVED** [review]

**Comment by Julievrz** [comment]
> @Julievrz I added the short description ;)

Thank you 😄

**Review by Progi1984 — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by atomiix** [comment]
Thanks @Julievrz

**Pull request merged**
